/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("com.gradleup.shadow") version "9.3.0"
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.19"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven("https://nexus.sirblobman.xyz/public/")
    maven("https://oss.sonatype.org/content/groups/public/")
    maven("https://repo.nightexpressdev.com/#/releases/")
    maven("https://repo.dmulloy2.net/repository/public/")
    maven("https://repo.codemc.io/repository/maven-public/")
    maven("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    maven("https://repo.nightexpressdev.com/releases")
    maven("https://maven.enginehub.org/repo/")
    maven("https://repo.bg-software.com/repository/api/")
    maven("https://repo.codemc.org/repository/maven-public")
    maven("https://jitpack.io")
    maven("https://repo.maven.apache.org/maven2/")
}

dependencies {
    compileOnly("su.nightexpress.excellentcrates:ExcellentCrates:6.2.1")
    compileOnly("su.nightexpress.nightcore:main:2.7.12.3")
    compileOnly("su.nexmedia:engine:2.2.8")
    compileOnly("io.lumine:mythic:5.8.1")
    compileOnly("net.dmulloy2:ProtocolLib:5.4.0")
    compileOnly("com.sk89q.worldguard:worldguard-bukkit:7.1.0-SNAPSHOT")
    compileOnly("net.luckperms:api:5.4")
    compileOnly("me.clip:placeholderapi:2.11.6")
    compileOnly("fr.skytasul:beautyquests-core:0.20.0")
    compileOnly("com.github.sirblobman.combatlogx:api:11.6-SNAPSHOT")
    compileOnly("com.github.sirblobman.api:core:2.9-SNAPSHOT")
    compileOnly("com.fastasyncworldedit:FastAsyncWorldEdit-Core:2.15.0")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7") {
        exclude("org.bukkit", "bukkit")
    }

    implementation("org.xerial:sqlite-jdbc:3.46.0.0")
    implementation("com.github.stefvanschie.inventoryframework:IF:0.10.8")
    implementation("fr.skytasul:guardianbeam:2.4.1")
    implementation("org.quartz-scheduler:quartz:2.3.0")
    implementation("io.github.rapha149.signgui:signgui:2.2")

    paperweightDevelopmentBundle("io.papermc.paper:dev-bundle:1.21.4-R0.1-SNAPSHOT")
}

group = "me.twostinkysocks"
version = "3.0"
description = "BoxPlugin"
java.sourceCompatibility = JavaVersion.VERSION_21

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.shadowJar {
    archiveClassifier.set("")
    relocate("com.github.stefvanschie.inventoryframework", "me.twostinkysocks.inventoryframework")

    relocate("fr.skytasul.guardianbeam", "me.twostinkysocks.libs.guardianbeam")
}

tasks.build {
    dependsOn(tasks.shadowJar)
}