/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    id("io.canvasmc.weaver.userdev") version "2.4.4-SNAPSHOT"
    id("io.canvasmc.horizon") version "1.0.0"
    id("com.gradleup.shadow") version "9.4.2"
}

horizon {
    splitPluginSourceSets()
    accessTransformerFiles.from(
        file("src/main/resources/wideners.at"),
    )
}

val pluginShade by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

configurations.named("pluginCompileClasspath") {
    extendsFrom(pluginShade)
}

repositories {
    mavenLocal()
    mavenCentral()
    maven("https://nexus.sirblobman.xyz/public/")
    maven("https://oss.sonatype.org/content/groups/public/")
    maven("https://repo.nightexpressdev.com/#/releases/")
    maven("https://repo.dmulloy2.net/repository/public/")
    maven("https://repo.codemc.io/repository/maven-public/")
    maven("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    maven("https://repo.nightexpressdev.com/releases")
    maven("https://maven.enginehub.org/repo/")
    maven("https://repo.bg-software.com/repository/api/")
    maven("https://repo.codemc.org/repository/maven-public")
    maven("https://jitpack.io")
    maven("https://repo.maven.apache.org/maven2/")
}

dependencies {
    compileOnly("su.nightexpress.excellentcrates:ExcellentCrates:6.2.1")
    compileOnly("su.nightexpress.nightcore:main:2.7.12.3")
    compileOnly("su.nexmedia:engine:2.2.8")
    compileOnly("io.lumine:mythic:5.8.1")
    compileOnly("net.dmulloy2:ProtocolLib:5.4.0")
    compileOnly("com.sk89q.worldguard:worldguard-bukkit:7.1.0-SNAPSHOT")
    compileOnly("net.luckperms:api:5.4")
    compileOnly("me.clip:placeholderapi:2.11.6")
    compileOnly("fr.skytasul:beautyquests-core:0.20.0")
    compileOnly("com.github.sirblobman.combatlogx:api:11.6-SNAPSHOT")
    compileOnly("com.github.sirblobman.api:core:2.9-SNAPSHOT")
    compileOnly("com.fastasyncworldedit:FastAsyncWorldEdit-Core:2.15.0")
    compileOnly("com.github.MilkBowl:VaultAPI:1.7") {
        exclude("org.bukkit", "bukkit")
    }

    includeLibrary("org.xerial:sqlite-jdbc:3.46.0.0")
    includeLibrary("fr.skytasul:guardianbeam:2.4.1")
    includeLibrary("org.quartz-scheduler:quartz:2.3.0")
    includeLibrary("io.github.rapha149.signgui:signgui:2.2")

    pluginShade("com.github.stefvanschie.inventoryframework:IF:0.10.8")

    paperweight.paperDevBundle("1.21.4-R0.1-SNAPSHOT")
    horizon.horizonApi("1.0.0.+")
}

group = "me.twostinkysocks"
version = "3.0"
description = "BoxPlugin"
java.sourceCompatibility = JavaVersion.VERSION_25

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(25))
}

tasks.named<Jar>("pluginJar") {
    from(pluginShade.map { file ->
        if (file.isDirectory) file else zipTree(file)
    }) {
        exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA", "META-INF/MANIFEST.MF")
    }
}