/*
 * This file was generated by the Gradle 'init' task.
 */
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = "Canvas"
            url = uri("https://maven.canvasmc.io/public")
        }
    }
}

rootProject.name = "aetherplugin"
